@extends('layouts.landing')

@section('title')
@lang('app.homepage')
@endsection


@section('content')
 <!-- bloc-29 -->
 <div class="bloc bgc-persian-red d-bloc" id="bloc-29">
    <div class="container ">
        <div class="row">
            <div class="col">
                <h1 class="mg-md text-lg-center tc-white text-center h1-bloc-29-style"><strong>Terms and Conditions</strong></h1>
            </div>
        </div>
    </div>
</div>
<!-- bloc-29 END -->
<!-- bloc-30 -->
<div class="bloc tc-liver bgc-white l-bloc" id="bloc-30">
    <div class="container bloc-md">
        <div class="row">
            <div class="col-lg-10 offset-lg-1">
                <h5 class="mg-md text-lg-center tc-persian-red">Please read our terms and conditions carefully<br></h5>
                <p>The application shall work as an online platform intermediate between the delivery representative on one hand and the customer on the other hand where it allows the customer to communicate with the delivery representative to do
                    his orders. Also, the application shall provide the services of charging cards to its customers according to the following terms and conditions:<br></p>
                <p class="p-margin-left"><strong>Section 1: Definitions of Terms<br></strong>In this agreement unless otherwise required by the context, the following terms shall have the meanings referred to.<br><br>“The application”, “we”, “First Person Pronoun” or
                    “Possessive Pronoun” shall refer to the application “We Deliver” and Amwaj Tech. c.<br><br>“User”, “you” or "your” shall refer to each person who visit or uses the application in any of its forms whether he is a delivery representative
                    or customer etc.<br><br>“Delivery Representative” is each person doing the delivery from the stores, delivery of the package or delivery of cargos among the cities at the request of the customer.<br><br>“Delivery Services”
                    shall refer to the delivery services done by the delivery representative in the interest of the customer and they shall include the delivery from stores, delivery of package and delivery of cargos.<br><br>“Purchases” shall
                    refer to the goods and products whatsoever whose purchase and delivery are ordered by the customer from the delivery representative.<br><br>“Content” refers to all texts, information, data, photos, logos, videos, advertisements
                    and all what is published by the user via the application.<br><br>“Agreement” shall refer to the conditions, terms, privacy policy, all pages of the application, descriptions of services, all information, the content of services,
                    all instructions and the special agreements made between the application on one hand and any of the application users on the other hand as well as the contracts connected with the terms and conditions.<br><br>“Parties to Agreement”
                    shall refer to the application on one hand as (a first party to the contractual relationship) and any person visiting the application, using it, registering an account in the application, providing any of the services of the
                    application or benefiting from our services in any way on the other hand as (a second party to the contractual relation).<br><br><strong>Section 2: Legal Scope of Our Services<br></strong>(1) The application “We Deliver” works
                    as an intermediate online platform that allows the communications among the customers and delivery representative and our role doesn&rsquo;t exceed that. We don&rsquo;t have a supervisory or monitoring authority over the delivery
                    representative. We don&rsquo;t represent the customers and we aren&rsquo;t agents of customers. Moreover, the provisions of labor, agency, sponsorship laws and other legal provisions connected with the legal liability for the
                    acts of servants or third parties shall not apply to us. You expressly agree on the nature of our work and role and you deal via the application out of these terms.<br><br>(2) The application “We Deliver” shall not be deemed
                    to be an internet service provider, shelter provider or information content provider. Also, it shall not be treated as a publisher of any content published via the application or via any property available for communication
                    via the application including messages, chatting etc.<br><br>(3) You know of and agree on the exemption of the application “We Deliver” from any liability arising from the acts of third parties. Whether he is a user, delivery
                    representative or customer etc.<br><br><strong>Section 3: Legal Nature of Terms and Conditions<br></strong>(1) This agreement shall be deemed to be the entire and final agreement between the application “We Deliver” on one
                    hand and any person visiting or using the application or any of its features or advantages on the other hand.<br><br>(2) This agreement shall be deemed to be a valid contract satisfying the legal conditions and elements and
                    shall be enforceable against all said parties. Its provisions and obligations shall be binding on all of them and neither party may derogate from it or terminate it since it has resulted in its legal effects.<br><br>(3) All
                    parties declare that this agreement forms the entire agreement among them. They declare that they didn&rsquo;t rely on any emphasis whether oral or written for accepting this agreement other than the provisions stated herein.<br><br>(4)
                    The description of the services and the subsequent pages of the application prepared by the application “We Deliver” shall form an integral part of this agreement.<br><br>(5) The amendments of this agreement shall have the
                    same legal provision and effect of this agreement.<br><br><strong>Section 4: Making Available Services<br></strong>(1) The application always attempts to make available its electronic services in the ideal way and uses in this
                    regard all the tools, equipment, devices, programs and the means of protection necessary for making available the services in addition to taking all the necessary legal procedures.<br><br>(2) The application doesn&rsquo;t guarantee
                    that the services or part of them work on all mobile phone. Also, for the devices on which the application works, there might be a delay or breakdowns due to a breakdown in the internet. Consequently, you exempt us from liability
                    therefor.<br><br>(3) In the course of providing our services, we provide the full support to the customer, delivery representative and users.<br><br><strong>Section 5: Consent and Capacity<br></strong>(1) You declare that you
                    have the legal capacity necessary for concluding and accepting this agreement.<br><br>(2) It is stipulated for the user of “We Deliver” that he has the legal capacity necessary for concluding contracts and we shall not be responsible
                    for ascertaining the capacity of any of the users of the application.<br><br>(3) With your use of the services of “We Deliver” you agree on this agreement and you declare are that you are legally bound by the terms and conditions
                    provided for in this document or its amendments.<br><br><strong>Section 6: Digital Signature<br></strong>(1) As for services requiring registration: Through your registration to get an account via the application or via clicking
                    for accepting the conditions of the service upon claiming so via the application, you shall be considered to have implemented this agreement and the other conditions of the service online and it shall be legally enforceable
                    for you from the date of registering your account or from the date of clicking for accepting the conditions of the service.<br><br>(2) As for services not requiring registration: your use of these services shall be deemed to
                    be an express consent by you to the terms and conditions provided for in this document and all the other policies and you shall be legally bound by them from the date of this use.<br><br><strong>Section 7: Conditions of Using Application<br></strong>(1)
                    It shall be stipulated that the natural person registers in the application in his true name and not in an alias, untrue or misleading names the user must be an adult. When you register as a natural person, you shall represent
                    yourself only because the account is based on the personal consideration.<br><br>(2) In case you register in the application with a personal account, you know that you represent yourself.<br><br>(3) It is stipulated that the
                    user puts his photo in his account and not any photo of a third party or a photo that doesn&rsquo;t express the user.<br><br>(4) You promise the instructions of the application in relation to your account including the methods
                    of using the account or the additional services as well as all precautions of use.<br><br>(5) You promise to make available the information and documents necessary and which is required by the application from you at any time
                    whether during the participation with us and the registration of your account or during the provision of services to you after registering your account.<br><br>(6) The user undertakes to precisely enter the information required
                    to be entered in the application and he shall be responsible for regularly reviewing this information for the purpose of correcting, modifying or renewing it as long as you have new information regarding this and you are required
                    to keep all the data and documents proving that.<br><br>(7) All the information you disclose must be real, updated and correct and express yourself and match with what is required in the registration form we have.<br><br>(8)
                    In case you have provided incorrect, unprecise, non-synchronized, or incomplete information or in case we have reasonable reasons to suspect that this information is incorrect, unprecise, non-synchronized, in complete or inconsistent
                    with this agreement of use and without prejudice to any other rights under this agreement or the law, we will suspend or cancel your membership.<br><br>(9) The user undertakes that he is responsible for maintaining the confidentiality
                    of the information in his account such as the user name and password and that he is responsible for any disclosure to third parties in relation to this information. Also, he is responsible for any use done by any person to
                    whom he disclosed this confidential information.<br><br>(10) The user undertakes to report immediately in case of penetrating the account or its theft as well as discovering any illegal use of this account in the application
                    in order for us to be able to take the technical actions necessary for maintaining the account.<br><br>(11) You may not use another person&rsquo;s account at any time without having an express consent from “We Deliver”.<br><br>(12)
                    The user shall be bound to notify us in case he discovers any illegal use of the application, any of the services or credit cards.<br><br>(13) We reserve the right to cancel the account that haven&rsquo;t been confirmed yet
                    or are inactive for a long time.<br><br>(14) The use of “We Deliver” might be coupled with making available services or content of other bodies that aren&rsquo;t under our control. Consequently, you declare that other conditions,
                    provisions and policies of privacy apply to your use of the services and content of the bodies not belonging to us.<br><br><strong>Section 8: Terms and Conditions of Customers<br></strong>(1) The customer shall be solely liable
                    for the account connected with his mobile phone and he shall be liable for any illegal use not permitted that is done via his account in the application.<br><br>(2) The customer knows and acknowledges that the services he receives
                    via the application are done by delivery representative without any intervention by the application “We Deliver”.<br><br>(3) The customer shall be solely liable for the correctness of delivery addresses he gives to delivery
                    representative and he shall incur any liability arising from the delay as a result the wrong addresses of delivery. Also, he shall incur the liability in case the delivery representative couldn&rsquo;t deliver the purchases,
                    package and cargos to him as a result of the wrong address, above mentioned.<br><br>(4) The customer shall undertake that the cargos, package and purchases whose delivery is required from the delivery representative via the
                    application shall be legal and go with the laws in force and shall not involve any drugs, wine, weapons, ammunitions, valuables that exceed 3500 SAR ,or any other items whose circulation is prohibited according to the laws
                    in force and the customer shall allow the representative to have access to his personal identity and to inspect the items whose delivery is required to make sure that they correspond to the preceding stipulations and the liability
                    of the customer and the representative shall be joint in case they breach this obligation without any original or ancillary liability of the application.<br><br>(5) The customer shall undertake not to order the delivery of
                    any items or products that are quickly spoiled, damaged or fragile for ensuring the high quality of the delivery act. Also, the customer shall be bound not to send any precious items or sums of money and he only shall incur
                    all the risks in case of ordering the delivery representative to deliver them.<br><br>(6) The customer shall be bound to pay for the purchases and the specified delivery fee in the event that the value due for the service is
                    not paid, or if the purchases are not received by the service provider, we have the right to ban the customer and not to remove the ban on the customer until the amounts due are paid to the customer<br><br>(7) The customer
                    shall be bound that his evaluation of the service provided by the delivery representative doesn&rsquo;t involve any insult or bad names and that the criticism or evaluation is within the limits legally permitted.<br><br>(8)
                    The customer knows and declares that we aren&rsquo;t an employer and don&rsquo;t have a monitoring or supervisory authority over the delivery representatives and that they are completely independent in their work.<br><br>(9)
                    The customer declares that we don&rsquo;t represent him against third parties and we aren&rsquo;t considered to be his agent and he is personally liable to the delivery representative in case of breach of the conditions and
                    provisions provided for in this agreement or in case of breach of the legal texts and provisions in force inside the Kingdom of Saudi Arabia.<br><br>(10) The customer knows and agrees that the application shall not incur any
                    liability for the loss of items whose delivery is ordered, their appropriation, decrease or any damage caused to them and the role of the application shall be limited to connecting the customer with the delivery representative
                    without intervening in the delivery act or providing and guarantee in relation to the items whose delivery is ordered.<br><br>(11) In case of the change by the customer of his mobile phone number or the assignment by him of
                    it to third parties, he undertakes to notify us of the new number and to activate the account once more with the methods of activation approved by us.<br><br>(12) The customer shall be bound to treat the delivery representative
                    in a good way.<br><br>(13) The customer shall be bound not to communicate with the delivery representative or give orders to him outside the framework applied within the application. In case of the breach by him of this obligation,
                    the application shall be entitled to permanently or temporarily suspend his use of the application as well as reserving all our other legal rights.<br><br><strong>Section 9: Terms and Conditions of Delivery Representative<br></strong>(1)
                    The registration by the delivery representative with us shall be based on the personal consideration. Consequently, he shall not be entitled to assign the account to third parties and not to authorize other than himself to
                    carry out the acts of driving he accepted to do.<br><br>(2) The delivery representative shall be prohibited from registering with us in more than one account and in case we discover this, we shall be fully entitled to suspend
                    or to terminate their account in the application.<br><br>(3) The delivery representative shall be deemed to be the first and last person responsible for the account connected with his mobile phone and the delivery representative
                    shall be liable for any illicit or unauthorized use that is done via his account in the application.<br><br>(4) The delivery representative acknowledges that he is personally liable for doing the acts of driving without any
                    liability of the application “We Deliver”.<br><br>(5) The delivery representative promises to get all the work permits necessary according to the laws in force within the Kingdom of Saudi Arabia.<br><br>(6) The delivery representative
                    promises to get all the licenses and legal documents necessary for the vehicle in which he gets while driving and he acknowledges that these licenses and papers have been issued from their legal sources without any liability
                    of the application. Also, he acknowledges that any vehicle in which he gets while driving isn&rsquo;t belonging to the application and he shall be personally liable for this vehicle and for all contraventions and accidents
                    that might occur while driving. He acknowledges that we don&rsquo;t provide any type of insurance as for the vehicle and we shall not be liable for compensating him or third parties for any damages that might take place while
                    driving.<br><br>(7) The delivery representative must have a valid driving license in force in the city in which he exercises his activity and it is stipulated that he renews it at the legally determined dates and he acknowledges
                    the validity and legality of this license and that he has got it from its legal sources and he shall be criminally responsible in case of otherwise.<br><br>(8) The delivery representative shall be bound to carry out the driving
                    according to the agreement concluded between him and the customer without any of our legal liability. Also, the delivery representative shall be bound to carry out his functions according to the agreement concluded between
                    him and the customer without any of our legal liability.<br><br>(9) The delivery representative shall be bound to carry out the acts of driving within the legally authorized areas and he promises to get away from the areas
                    whose entry is prohibited.<br><br>(10) The delivery representative shall be bound to make sure of the cargos and package before receiving it and that they don&rsquo;t involve any items in breach of the laws in force not to
                    be legally liable, Also, he shall be bound not to buy any items or products whose circulation is prohibited , different materials such as prepaid cards, gift cards, passes, financial groups (stamps, cash, etc.) or valuables
                    that exceed 3500 SAR ،In all cases, the liability of the delivery representative and customer shall be joint in case they breach this obligation without any legal original, ancillary or joint liability of the application.<br><br>(11)
                    The delivery representative shall be bound to bring an invoice of the purchases he bought at the request of the customer.<br><br>(12) The delivery representative shall be bound to keep the items he delivers safe in the interest
                    of the customer as well as not opening them after receiving them and not to ship them in a way that causes damage or destruction of these items.<br><br>(13) The delivery representative acknowledges not to claim the payment
                    of any amounts more than those agreed upon within the application from the customer.<br><br>(14) The delivery representative acknowledges that he isn&rsquo;t our employee and we aren&rsquo;t an employer and we don&rsquo;t have
                    a supervisory or monitoring authority over him and he works under his personal liability without any of our contractual or legal liability.<br><br>(15) The delivery representative knows and acknowledges that we don&rsquo;t
                    provide any medical insurance to him while driving. The relationship between delivery representative and the application isn&rsquo;t an employment relationship.<br><br>(16) The delivery representative knows and acknowledges
                    that we don&rsquo;t have a working relationship or representation, agency etc. In case of the breach by the customer of any of the rights of delivery representative&rsquo;s rights, delivery representative shall be entitled
                    to take all his legal actions without having recourse to or against us.<br><br>(17) You shall not be authorized to use the operations done within the application in another websites or applications and not to exploit your evaluation
                    in the application in another website or applications.<br><br>(18) In case of the change of your mobile phone No or assignment of it to third parties, you promise to report the new No to us and to activate the account once
                    more with the activation methods approved by us.<br><br>(19) Delivery representative shall be bound by the well treatment of the customer and by not doing wrong to us.<br><br>(20) Delivery representative shall be bound not
                    to communicate with the customer or to carry out services outside the framework applied within the application. In case of the breach by him of this obligation, the application shall be entitled to permanently or temporarily
                    suspend his use of the application as well as reserving all our other legal rights<br><br>(21) The delivery representative decides to abide by the trust in the value and truth of the operations, and the delivery representative
                    agrees in the event of any tampering or misuse of the service to the customer in a manner that directly or indirectly impairs the application, the delivery representative will be subject to stopping his services in addition
                    to the right of "We Deliver" Collecting a misuse penalty of 1,500 SR, in addition to the "We Deliver" right to claim compensation that resulted from this fraud or misuse.<br><br><strong>Section 10: Payment Policy<br></strong>(1)
                    The delivery fee shall be calculated by the application and this fee shall be calculated according to the distance between the receipt point and the delivery point in kilometers.<br><br>(2) The customer shall pay for the delivery
                    in addition to the value of purchases to the delivery representative in cash provided that the value of commission shall be debited from the account of delivery representative in the application.<br><br>(3) In case the commission
                    percentage due to us in the account of the delivery representative in the application is minus 50 Saudi Riyals, the delivery representative shall be bound to transfer our dues via the means of electronic payment approved by
                    us.<br><br>(4) The application doesn&rsquo;t agree to incur the consequence of any mistake related to the payment process done by the customer or delivery representative. Also, it doesn&rsquo;t incur the consequence any hacking
                    act or deception connected with credit cards or the bank accounts of the customer or delivery representative.<br><br>(5) The customer and delivery representative shall incur all the banking fees connected with the transfer
                    of funds or the payment of the prices of charging cards and commissions.<br><br>(6) The amounts paid by the customer to the application shall be final and may not be modified either in increase or decrease and they may not
                    be recovered except with the consent of the application.<br><br>(7) The commission paid by the delivery representative to the application shall be final and may not be modified either in increase or decrease and they may not
                    be recovered except with the consent of the application<br><br>(8) The application is not responsible in the event that the customer pays more than what appeared to him on the invoice and does not bear any compensation for
                    that matter.<br><br>(9) The application of “We Deliver” shall reserve the right to modify the policies of fees and payment at any time it considers appropriate.<br><br><strong>Section 11: Return Policy<br></strong>(1) The customer
                    knows that the application doesn&rsquo;t shall any of the purchases made available by the delivery representative. As a result, we don&rsquo;t provide any refund ability policies and the refund ability shall be done according
                    to the refund ability policy of the shop from which the delivery representative bought the purchases.<br><br>(2) The delivery representative shall purchase the goods in the interest of the customer from the various stores,
                    restaurants and shops and in this case the customer shall comply with the refund ability policies of each store, restaurant and shop. In case the customer refuses to implement these policies and to receive the purchases from
                    the delivery representative, the customer shall be bound to pay for the purchases in addition to paying of the delivery.<br><br>(3) In case the delivery representative returns the purchases at the request of the customer, the
                    customer shall be bound to pay for the delivery and return of the purchases to the place from which they were purchased to the delivery representative.<br><br>(4) The application shall accept the refund ability in view of the
                    charging cards before sending the charging card No to the customer. But in case of sending the charging card No to the customer at his request, the application can&rsquo;t return the paid amount.<br><br><strong>Section 12: Terms and Conditions of Evaluation<br></strong>The
                    customer can evaluate the delivery representative and the delivery representative can evaluate the customer and evaluations shall be subject to the following terms and conditions:<br><br>(1) The evaluations by the customer
                    and the delivery representative must be true and don&rsquo;t cause any wrong to any party or person.<br><br>(2) It is prohibited during the evaluations to expose names, persons, institutions, companies, symbols or to defame
                    or do wrong to them in any way. Also, it is prohibited to use religious slogans or phrases contempting cultures or peoples or conflicting the applicable order.<br><br>(3) In all cases, “We Deliver” shall not incur any liability
                    in view of the truth of evaluations and their legality and we shall not incur any liability for illegal evaluations for which those who wrote them shall be liable.<br><br>(4) “We Deliver” shall reserve the full right to review
                    and delete any illegal evaluations and to suspend or cancel the membership of the person doing wrong. The non-removal of the illegal evaluations shall not mean to a participation or a consent to the publication. Our right to
                    review the evaluations must not be understood to be a legal obligation lying on us and you have to report to us in case of the existence of illegal evaluations to take the suitable action for them.<br><br>(5) The application
                    shall reserve its rights to refuse to publish any evaluations at any time in case they conflict with the preceding provisions.<br><br>(6) In all cases, we shall reserve the full right to resort to judiciary and to get all the
                    appropriate compensations in case the evaluations result in damages to the application owned by us while reserving by the prejudiced person and the society of his right to the criminal punishments.<br><br><strong>Section 13: Copyrights<br></strong>(1)
                    The application and ideas expressed within it shall be our intellectual property rights. Any imitation or plagiarism of the application or some of its services (including ideas, texts, symbols and software) shall be deemed
                    to be a violation of our copyrights for which we will take all the legal procedures against the perpetrator of the said violations.<br><br>(2) All the contents included or available within the services of the application “We
                    Deliver” such as (texts, logos, pictures, graphs, voice, recordings, icon buttons, digital contents, materials that are uploaded, software and collection of data) shall be the property of the application and shall be protected
                    by the Kingdom of Saudi Arabia laws and the international copyrights laws.<br><br>(3) The collection of all data inserted in the service of “We Deliver” or making it available by any of our services shall be exclusively and
                    privately owned by the application “We Deliver” and protected under the Kingdom of Saudi Arabia laws of copyrights and the international ones and also shall be protected under the international conventions in force such as
                    Bern Convention and TRIPS Agreement.<br><br><strong>Section 14: Trademarks<br></strong>(1) “We Deliver” and logos connected with it shall be our trademarks and/or our services marks.<br><br>(2) Pictures, logos, headers of pages,
                    icon buttons, texts and services names shall be trademarks and commercial designs of the application “We Deliver”.<br><br>(3) Reproduction of trademarks or commercial designs of the application “We Deliver” in any media or
                    advertising means shall be prohibited without a written permission from us.<br><br>(4) Trademarks and commercial designs of the application “We Deliver” may not be used for contacting any product or service that doesn&rsquo;t
                    belong to us not to cause harm to the position and credibility of the application “We Deliver” or to cause harm to its customers.<br><br><strong>Section 15: Granted Licenses<br></strong>(1) Through being bound by the conditions
                    of use or any conditions of the service and through paying any applied fees, the application grants you a limited and unexclusive license that is non-assignable and may not be subleased to have access to the non-commercial
                    use of the services of the application “We Deliver”.<br><br>(2) This license doesn&rsquo;t involve the reselling or any commercial use of any of our services or their content. Also, it doesn&rsquo;t involve any copy of the
                    information available about the account in the favor of third parties or the use of means of getting data as well as any use of the tools of collecting and eliciting the similar data.<br><br>(3) You may not reproduce or make
                    typical copy of this application, copy, sell, resell any part of it or use it in a different way for purposes of commercial or non-commercial exploitation of it without having an express written consent by the application “We
                    Deliver”.<br><br>(4) You may not use any descriptive marks or any other “hidden text” which exploits the name “We Deliver” or its trademark without an express written consent by the application.<br><br>(5) You agree not to
                    use the application “We Deliver” or any service provided via it in an illegal, deceitful or antisocial way as we determine.<br><br>(6) You agree not to send any messages characterized by being racial or containing cursing and
                    defamation or bad names, porn pictures or those characterized in general by being decadent.<br><br>(7) You shall be prohibited as a user to publish any links of another applications or websites within the application or involving
                    software or viruses or aiming at any deception or online hacking.<br><br>(8) You shall be prohibited in any way to intervene the working method of the application or to publicize in any way that you represent us contrary to
                    reality.<br><br>(9) You may use our services in the form only legally permitted and according to the conditions of the agreement.<br><br>(10) The licences granted by us shall terminate in case you don&rsquo;t comply with these
                    conditions of use or any conditions of another service.<br><br>(11) All rights not expressly granted to you to these conditions of or any conditions of another service shall be reserved by the application “We Deliver”.<br><br><strong>Section 16: Telecommunications<br></strong>(1)
                    You agree on getting telecommunications from us and we will communicate with you via the mobile phone number or through the other services of the application “We Deliver”.<br><br>(2) You agree that all agreement, notices, disclosures
                    and other telecommunications done by us online satisfy all the legal conditions as if they were written with all their legal effects.<br><br>(3) The application “We deliver” requires your consent during the registration process
                    to sending messages on your mobile phone or via the application for promotion purposes to inform you of any changes, advantages or new activities added to your application.<br><br>(4) In case you decide at any time that you
                    don&rsquo;t want to receive promotion messages, you can deactivate the receiving of these messages through correspondence with us. But in this case we don&rsquo;t ensure that you will enjoy our services fully.<br><br><strong>Section 17: Notices<br></strong>(1)
                    Any notices you like to send to the application “We Deliver” must be sent through the features specified within the application. Any notices sent outside the application shall not be considered.<br><br><br>a. Any notices the
                    application “We Deliver” likes to send to you shall be either by publicizing them via the application or sending them to you via the mobile phone number you provided us with during the registration process. You are supposed
                    to have known of the notice as soon as the notice is publicized via the application or with the lapse of 24 hours from the time at which the message was sent to you.<br><br><strong>Section 18: Taxes and Fees<br></strong>(1)
                    The user shall be bound to pay all government taxes levied on the activity he exercises via the application.<br><br>(2) The user shall be bound to pay the fees of telecommunications companies for the purpose of getting the
                    data connected with the access to the internet.<br><br><strong>Section 19: Assignment of Rights and Obligations<br></strong>(1) The application “We Deliver” shall be entitled to transfer all the rights mentioned in this agreement
                    to third parties without any objection by the user. All shall be bound to perform all their obligations mentioned in this agreement to the assignee immediately they are notified of the assignment. The assignee shall be entitled
                    to take all the legal procedures against whoever doesn&rsquo;t perform his obligations under this agreement.<br><br>(2) You may not assign your obligations and rights under this agreement or authorize a third party to manage
                    your account in the application except after getting a written consent from us.<br><br><strong>Section 20: Modifications<br></strong>(1) We may amend or update these terms and conditions of the agreement in relation to the
                    use of the application without notifying you thereof. Thus, you have to have access to this agreement regularly.<br><br>(2) You may not change any terms of this agreement amend or replace them without a written consent from
                    the application “We Deliver”.<br><br>(3) You agree to be bound by all the additional conditions and terms that will be made available to you in connection with the use of any of the services available via the application. These
                    additional conditions and terms are attached to this agreement.<br><br>(4) We may at any time conduct modifications or improvements we consider appropriate and necessary for increasing the efficiency of the application. The
                    user shall be bound with any directions or instructions provided by the application to him in this regard.<br><br><strong>Section 21: Cancellation of the Agreement<br></strong>(1) We shall be entitled at any time to cancel
                    all or some of the services we provide. Also, we shall be entitled at any time to cancel the terms and conditions or to replace them with another terms and conditions.<br><br>(2) This agreement shall be deemed to have been
                    automatically rescinded in case of your breach of our financial rights or commissions due to us or causing legal problems to us or the parties to this agreement or to third parties or in case of your breach of any clause or
                    paragraph of the terms and conditions of this agreement or in case of not documenting your information or suspension of the application activity. In all preceding cases, we shall be entitled to have judicially recourse against
                    your under this agreement in case the cause of rescission is due to your breach of its provisions.<br><br><strong>Section 22: Legal Liability of the Parties to the Agreement<br></strong>(1) You expressly agree that you are
                    personally liable for the use by you of the application “We Deliver”.<br><br>(2) You shall be bound by all the laws and regulations in force within the Kingdom of Saudi Arabia in relation to your use of the application and
                    shall incur all the liability arising from your breach of the laws and regulations also you shall be bound by all the terms and conditions provided for in this agreement.<br><br>(3) You shall be liable for the lack of the serious
                    and credible use of the application and you shall be bound to compensate for any losses or damages caused to the application as a result of any illegal use or not permitted by us.<br><br>(4) The users shall provide us with
                    their information and mobile phone number and shall be personally liable for that. Consequently, they shall incur the civil liability and criminal responsibility in case these numbers are stolen or not registered in their names
                    or belonging to another person&rsquo;s.<br><br>(5) You acknowledge your full legal liability in case of your breach of all the clauses provided for in this agreement and we shall be entitled to take all the actions against
                    you including the suspension or cancellation of your membership or resorting to judiciary.<br><br>(6) The prejudiced party who is harmed as a result of the breach by any of the parties to this agreement has to take all the
                    necessary legal procedures against the party who committed the illegal act without having recourse to or against us. The prejudiced party has to notify us of the breach only to take an action within the application either through
                    suspending membership or permanent ban on it.<br><br>(7) The penalties imposed by the application “We Deliver” on the parties to this agreement shall not affect adversely the right of each party to take all the legal procedures
                    he considers appropriate according to his discretion without having recourse against us and without the liability of the application.<br><br>(8) The application “We Deliver” doesn&rsquo;t ensure to take actions against all
                    the violations of this agreement. Not taking legal procedures in relation to any of the cases of violation shall not mean a waiver of our right to take these procedures at any time we consider appropriate.<br><br><strong>Section 23: Limits of Our Liability<br></strong>(1)
                    We provide our services “as they are available” without any promises or guarantees of any kind whether express or implied through the use of this application, it&rsquo;s content or services provided by it.<br><br>(2) The application
                    “We deliver” doesn&rsquo;t provide any guarantees that this application, its servers or the messages are free from viruses or other harmful components.<br><br>(3) The application “We deliver” doesn&rsquo;t provide any guarantee
                    and shall not incur any liability in relation to the modernity, commonness, precision and quality of information received by the user via the application.<br><br>(4) The liability of using or depending on the information that
                    is received or reached by the user through the services of the application “We deliver” shall completely lie on this user.<br><br>(5) You declare that the application “We deliver” is an internet – based service and in spite
                    of exerting our best to keep information safe, we can&rsquo;t guarantee that information received or transmitted by the user while using the application is safe at all times.<br><br>(6) The application “We deliver” can&rsquo;t
                    assure that each user of the application is actually the person he claims to be.<br><br>(7) We might at anytime modify, suspend or interrupt the services of the application “We deliver” without sending a notification to you
                    thereof. Also, we might suspend your use of our services in case you violate these conditions and terms or in case you have misused these services from our point of view.<br><br>(8) Without prejudice to its other rights, the
                    application “We deliver” shall be entitled to suspend or cancel your membership or your access to the application at any time without notice and for any reason and to cancel this agreement.<br><br><strong>Section 24: Compensations<br></strong>(1)
                    The application shall not be liable in all cases for any direct, indirect or dependent losses, loss of profits or damage to the fame whatsoever as a result of disclosing your user name and/or password.<br><br>(2) The application
                    “We deliver” shall not be legally liable for losses or damages whatsoever that might arise from using this application including but limited to the direct and indirect damages.<br><br>(3) The application “We deliver”, its officials
                    and employees shall not be legally liable to you or to another party for any direct or indirect loss or any other cost that might arise from, in connection with the performance of this agreement or the provisions of our services.<br><br>(4)
                    The user has to protect the application “We deliver” and its employees, defend them and compensate them for any losses resulting from any action or claim connected with the application or from an act or negligence by the user,
                    his representative or agents.<br><br>(5) You agree to compensate the application “We deliver” and to acquit its liability as well as defending it against all the actions and claims, losses and expenses (including attorney's
                    fees) brought or claimed by third parties as a result of your use of application or due to the violation of these conditions and terms or the breach of the rights of the other users.<br><br><strong>Section 25: Applicable Law and Competent Courts<br></strong>(1)
                    This agreement shall be governed by the laws in force within Kingdom of Saudi Arabia.<br><br>(2) Judiciary within Kingdom of Saudi Arabia shall have jurisdiction over any dispute that might arise from the interpretation or
                    performance of this agreement.<br><br>(3) In case any of the provisions of this agreement becomes illegal or unenforceable, the legality and enforceability of the other provisions will not be affected.<br><br><strong>Section 26: Language<br></strong>(1)
                    Arabic text of this agreement shall be the certified text in relation to interpretation and application its terms and conditions.<br><br>(2) In case of conflict between the Arabic text and the translated text of this agreement,
                    the Arabic text shall prevail<br></p>
            </div>
        </div>
    </div>
</div>
@endsection